# Generated by Django 5.2.8 on 2025-11-18 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_studentinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentinfo",
            old_name="country_preference",
            new_name="country",
        ),
        migrations.RenameField(
            model_name="studentinfo",
            old_name="course_preference",
            new_name="target_country",
        ),
        migrations.RemoveField(
            model_name="studentinfo",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="target_course",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="full_name",
            field=models.CharField(max_length=120),
        ),
    ]
