# Generated by Django 5.2.8 on 2025-11-18 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_rename_country_preference_studentinfo_country_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentdocument",
            old_name="upload_date",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="studentdocument",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="studentdocument",
            name="status",
        ),
        migrations.RemoveField(
            model_name="studentdocument",
            name="student",
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="document_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="file",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
