# Generated by Django 5.2.8 on 2025-11-20 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True, null=True)),
                ("experience_years", models.IntegerField(default=0)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rating", models.FloatField(default=0)),
                ("total_reviews", models.IntegerField(default=0)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="consultants/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsultantSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultants.consultantprofile",
                    ),
                ),
            ],
        ),
    ]
